#baseURL = 'https://embed-rayn.github.io/'
#languageCode = 'en-us'
#title = 'My New Hugo Site_test'

baseURL = "https://embed-rayn.github.io/" # ë¸”ë¡œê·¸ ê²½ë¡œ
languageCode = "ko-kr" # ì‚¬ìš© ì–¸ì–´
title = "paper review" # ì›¹ í˜ì´ì§€ íƒ€ì´í‹€
theme = "github-style" # í…Œë§ˆ
#googleAnalytics = "UA-123456-789"
#pygmentsCodeFences = true
#pygmentsUseClasses = true

[params]
  [params.author]  
    name = "bjpark" # ì´ë¦„
    description = "Hi my name is byeongjun park. My interest is AI." # ìê¸° ì†Œê°œ
    github = "embed-Rayn" # github ê³„ì •ëª…
#  linkedin = "yongckim" # linked in ê³„ì •ëª…
  email = "qwe1443@gmail.com" #ì´ë©”ì¼
  url = "https://embed-rayn.github.io/" # ì‚¬ì´íŠ¸ ì£¼ì†Œ
  keywords = "paper, review, AI" 
#  rss = true
  lastmod = true
  userStatusEmoji = "ğŸ˜€" # í”„ë¡œí•„ì‚¬ì§„ ì˜† ì´ëª¨ì§€
  favicon = "/images/github.png" # íŒŒë¹„ì½˜ì„¤ì •
  avatar = "/images/avatar.png" # í”„ë¡œí•„ ì‚¬ì§„ ì„¤ì •
  location = "Korea" # í˜„ì¬ ìœ„ì¹˜ ì„¤ì •

  [[params.links]]
    title = "algorithm" # organization link
    href = "https://www.acmicpc.net/user/zxcv9203"
		icon = "https://zxcv9203.github.io/images/boj.png"
#  [[params.links]]  í•˜ë‹¨ ì•„ì´ì½˜ ë§í¬ ì¶”ê°€
#    title = "Link2"
#    href = "https://yongckim.github.io/"
#   	icon = "https://zxcv9203.github.io/images/avatar.png"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
